# Generated by Django 5.0 on 2024-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
